# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-05 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='image',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
