# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-05 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170705_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
