# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-05 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170705_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='image',
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
