# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-05 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170705_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='text',
            field=models.CharField(max_length=2500),
        ),
    ]
